-- Structured profession navigation generated from the HorizonXI Wiki export.
return {
  ["Alchemy"]={
    name="Alchemy",
    page_url="https://horizonffxi.wiki/Category:Alchemy",
    recipes_url="https://horizonffxi.wiki/Category:Alchemy/All_Recipes",
    primary_guide_id="wiki_16227",
    primary_guide_title="Alchemy Guide by Arayne",
    ranges={
      ["0-10"]={ rank="Amateur", url="https://horizonffxi.wiki/Category:Alchemy/Amateur", blocks={
        "Level 0 - 10\010\0100-5 BEESWAX (5) - Fire Crystal, Beehive Chip x3, Distilled Water: Welcome to Alchemy, when you farm the chips, this will be your main source of cash, for a long time. In Gustaberg, there are a LOT of bees that you can farm. Make the chips into beeswax, and make a good amount of cash. Because this recipe is used a LOT by higher level alchemists, and many do not want to do the scut work. Use this to your advantage, and remember that a stack can get you around 10k, so do NOT cheat yourself out of cash, because it is needed. SAVE THE HONEY YOU FARM!\0105-9 CORNSTARCH (9) - Lightning Crystal, Millioncorn x2: Quick. Easy. Cheap. In and out, and to the next recipe.\0109-12 POISON DUST (12) - Lightning Crystal, Yellow Globe x2: Hold on to these dust, you will need them shortly.\010TEST ITEM: ANIMAL GLUE (7) - Fire Crystal, Bone Chip x2, Rabbit Hide, Distilled Water: This recipe is here as a go to for when you do guild points, as many of the recipes will be putting a status potion on a weapon. Never forget this recipe, and KNOW THAT YOU CAN MAKE MONEY ON IT WHEN YOU CAN HIGH QUALITY IT.",
      }},
      ["11-20"]={ rank="Recruit", url="https://horizonffxi.wiki/Category:Alchemy/Recruit", blocks={
        "Level 10 - 20\010\01012-16 MERCURY (16) - Lightning Crystal, Cobalt Jellyfish x4: Go to Bibiki Bay. Talk to Mep Nhapopoluko, buy as many cobalt jellyfish as you can afford. They are 9g each, so it shouldn\226\128\153t cost you too much. Synth ALL of them. Hold on to all of your mercury, and get ready for the next step. Then AH the rest of them. If done in moderation, this recipe is a great cash grab, as mercury sells quickly and well. It isn\226\128\153t as much cash as Beeswax, but it does sell faster, without having to farm. While on the way to Bibiki Bay and back, clear out the leeches. This will net you another boost in cash from the Bird Blood.\01016-18 POISON POTION (18) - Water Crystal, Mercury, Poison Dust: This recipe is a great recipe. It's a TEST ITEM, it's a great way to make money, and it only makes one potion per craft, meaning that there is no way a higher level crafter can come in and take the funds from you. These potions are needed for many Chains of Promathia fights, including the Promys and Diabolos, Dynamis - Bastok, and Dynamis - Windurst.\01018-20 ECHO DROPS (20) - Water Crystal, Honey, Sage, Distilled Water: Unless you High Quality on Silent Oil, you are LOSING MAJOR PROFITS on making it at this time. This recipe isn\226\128\153t much better if you didn\226\128\153t save honey, or ignored Beeswax for some reason, but I\226\128\153d rather spend the money on a somewhat lesser used material than the one that is going to set you back hardcore because you ran out of beeswax.\010TEST ITEM: POISON POTION (18) - See Above.",
      }},
      ["21-30"]={ rank="Initiate", url="https://horizonffxi.wiki/Category:Alchemy/Initiate", blocks={
        "Level 20 - 30\010\01020-28 BLINDING POTION (28) - Lightning Crystal, Mercury, Nebimonite:You will need Advanced support for this, and this recipe is a little more expensive than the Poison Flour version, but gives more skill, and you can accumulate the items quicker. You STILL have Mercury, right? Save one as a TEST ITEM.\01028-31 BLIND BOLT HEADS (31, Smithing 14) - Wind Crystal, Bronze Ingot, Blinding Potion, Animal Glue: Normally, I do these guides with the mindset of \226\128\156You don\226\128\153t need another craft to get to 60\226\128\157. The bolt head recipes are all the way up, so it is best to just get the 14 skill (Make sure to view MY GUIDE to get there quickly) and move on.\010TEST ITEM: BLINDING POTION- See above.",
      }},
      ["31-40"]={ rank="Novice", url="https://horizonffxi.wiki/Category:Alchemy/Novice", blocks={
        "Level 30 - 40\010\01031-32 ARTIFICIAL LENS (34) - Fire Crystal, Glass Fiber x2: Desynth some Goblin Masks for the Glass Fiber, and then attempt to make these. It isn't as fun as making your own Glass Fiber, but it will manage you this level. Try not to go further, because it gets more expensive if you're not High Quality frequently on the desynth.\01032-37 POTION (40) - Water Crystal, Lizard Tail, Distilled Water, Sage: This recipe is so cheap and convenient, it is a shame it is so high, and so close to the next convenient recipe. Avoid Firesand if you have no smithing or goldsmithing to make bullets.\01037-42 VITRIOL (42) - Water Crystal, Treant Bulb x2: The Bulbs are cheap on the Auction House, and the recipe this is used for is a very common one to use.\010TEST ITEM: FIRE SAND (40) - Earth Crystal, Bomb Ash x2, Sulphur: Just go make it. The stuff can be found at the NPCs. It is expensive this way, but manageable.",
      }},
      ["41-50"]={ rank="Apprentice", url="https://horizonffxi.wiki/Category:Alchemy/Apprentice", blocks={
        "Level 40 - 50\010\01043-45 ACID BOLT HEAD (45 Smithing 14 ) - Wind Crystal, Vitriol, Bronze Ingot, Animal Glue: These babies are used a LOT by Woodworkers for thieves. Make yourself some for your own use, and know that while it may not be better to HQ these, sell them on the Auction House, and then use the profits to buy your own, making your own bolts/arrows feels good. Period. You feel like you are self-sustaining.\01045-51 HOLY WATER (51) - Light Crystal, Distilled Water: This recipe is used a lot in CoP and anything that can curse. It is highly profitable. Tired of Beeswax? Welcome to another form of cash.\010TEST ITEM: FIRE SWORD (46) - Earth Crystal, Fire Sand, Iron Sword, Slime Oil: A popular low level sword. This is made in attempts to make Flame Swords, and dumped. Grab one off the Auction House.",
      }},
      ["51-60"]={ rank="Journeyman", url="https://horizonffxi.wiki/Category:Alchemy/Journeyman", blocks={
        "Level 50 - 60\010\01051-53 HOLY BOLT HEAD (53) - Wind Crystal, Holy Water x2, Bronze Ingot: A bridge to keep from blowing your brains out on sleeping potions.\01053-56 SLEEPING POTION (56) - Water Crystal, Chamomile, Poison Flour, Sleepshroom: I hate this craft. It isn\226\128\153t too bad, but it feels tedious. Blast through these levels, and don\226\128\153t look back. These also sell on the Auction House in stacks because of Maat Fights, but it isn\226\128\153t worth focusing on.\01056-61 VENOM DUST (61) - Lightning Crystal, Scorpion Claw x 2: This recipe is great for moving through the levels. Move on.\010TEST ITEM: HI-POTION (60) - Water Crystal, Sage, Malboro Vine, Distilled Water: Make or buy it. Move on.",
      }},
      ["61-70"]={ rank="Craftsman", url="https://horizonffxi.wiki/Category:Alchemy/Craftsman", blocks={
        "Level 60 - 70\010\01061-68 VENOM POTION (68) - Water Crystal, Venom Dust, Mercury: What did you expect, Holy Swords? Cermet? Nah, you just made a bunch of dust, turn it into a potion.\01068-72 PARALYSIS DUST (72) - Lightning Crystal, Three-Eyed Fish: Big fish energy here. Go to Qufim and talk to fishers, they\226\128\153re usually willing to part with these on the cheap.\010TEST ITEM: ACID KUKRI (67) - Mythril Kukri, Animal Glue, Vitriol: Probably best making this one, might be able to find one cheap though.",
      }},
      ["71-80"]={ rank="Artisan", url="https://horizonffxi.wiki/Category:Alchemy/Artisan", blocks={
        "Level 70 - 80\010\01072-78 PARALYZE POTION (78) - Water Crystal, Paralysis Dust, Mercury: What, did you expect Anima here? Oh yes, that caps at 75, but you only want to micro batch it until you get a few buyers to take their money from. Make a little anima, put it on the auction house, and sell your services, but ONLY once you hit 75. Unless you have a buyer that\226\128\153s willing to deal with your breaks and potential losses.\01078-81 BLOODY BOLT HEADS (81, Smithing 14) - Wind Crystal, Beastman Blood, Revival Root, Bronze Ingot: Your final Bolt head. This one is worth a lot of money, and you will be asked to make some, especially for woodworkers that want to make a big profit on bolts. Make to cap, and save some stacks to slow roll.\010TEST ITEM: X-POTION (77) - Water Crystal, Sage x2, Reishi Mushroom, Hecteyes Eye, Distilled Water: Crafted only, so you\226\128\153ll likely have to make it. Good luck!",
      }},
      ["81-90"]={ rank="Adept", url="https://horizonffxi.wiki/Category:Alchemy/Adept", blocks={
        "Level 80 - 90\010\01081-87 HOLY LEATHER (87) - Light Crystal, Ram Leather, Holy Water: This will sell slowly on the auction house because it is used for White Mage AF+1 gear. It also NPCs for a bit of cash, but it will be a slight loss unless bought on Auction House.\01087-91 MAMUSHITO (91) - Water Crystal, Paralyze Potion, Shinobi-Gatana, Animal Glue: Did\226\128\166 did I just recommend a weapon with a potion effect? Yes, yes I did.\010(ALT) 87-91 URUSHI (91, Woodworking 59, Smithing 21) - Fire Crystal, Lacquer Tree Sap x4, Iron Ore, Honey: Wow, another thing I haven\226\128\153t done; recommend a recipe outside bolt heads with lots of crafting subs. This will make you money from woodworkers, as well as skill. They make the sap, you make the Urushi, they make items to get to 100 skill with it, and you both profit from it. It is worth making.\010TEST ITEM: BLOOD SWORD (88) - Dark Crystal, Bastard Sword, Beastman Blood, Revival Tree Root: You will likely have to make this, but it is the last turn in, and feels good to make. Turn it in, and scream\226\128\166 welcome to hell\226\128\166",
      }},
      ["91-100"]={ rank="Veteran", url="https://horizonffxi.wiki/Category:Alchemy/Veteran", blocks={
        "Level 90 - 100\010\01091-96 PLATINUM NUGGET (96) - Fire Crystal, Panacea, Platinum Leaf: Between this and Panaceas, you want to try to hit 98. You will be a goldsmith\226\128\153s best friend and friend to elemental ore growers that fail to harvest an ore. This recipe is worth it, even if you\226\128\153re using the Panacea that is the next craft to make it.\01096-98 PANACEA (98) - Light Crystal, Philosopher\226\128\153s Stone, Mercury, Sulfur, Rock Salt: Philosopher Stones can be a pain to get, but they can also be plentiful. It will be a toss up at times. The idea is to cap out and make as many nuggies as you can and get a goldsmith to turn those into ingots for you. Make money and friends.\01098-100 PRO-ETHER (100) - Water Crystal, Dried Marjoram x3, Ahriman Wing x2, Wyvern Wing, Treant Bulb, Distilled Water: Wyvern wings and Ahriman Wings are going to be your hold up on these. HOARD THOSE UNTIL YOU GET TO THIS POINT! If you do, you may be able to power through those last few levels! Congratulations!",
      }},
    },
  },
  ["Bonecraft"]={
    name="Bonecraft",
    page_url="https://horizonffxi.wiki/Category:Bonecraft",
    recipes_url="https://horizonffxi.wiki/Category:Bonecraft/All_Recipes",
    primary_guide_id="",
    primary_guide_title="",
    ranges={
      ["0-10"]={ rank="Amateur", url="https://horizonffxi.wiki/Category:Bonecraft/Amateur", blocks={
      }},
      ["11-20"]={ rank="Recruit", url="https://horizonffxi.wiki/Category:Bonecraft/Recruit", blocks={
      }},
      ["21-30"]={ rank="Initiate", url="https://horizonffxi.wiki/Category:Bonecraft/Initiate", blocks={
      }},
      ["31-40"]={ rank="Novice", url="https://horizonffxi.wiki/Category:Bonecraft/Novice", blocks={
      }},
      ["41-50"]={ rank="Apprentice", url="https://horizonffxi.wiki/Category:Bonecraft/Apprentice", blocks={
      }},
      ["51-60"]={ rank="Journeyman", url="https://horizonffxi.wiki/Category:Bonecraft/Journeyman", blocks={
      }},
      ["61-70"]={ rank="Craftsman", url="https://horizonffxi.wiki/Category:Bonecraft/Craftsman", blocks={
      }},
      ["71-80"]={ rank="Artisan", url="https://horizonffxi.wiki/Category:Bonecraft/Artisan", blocks={
      }},
      ["81-90"]={ rank="Adept", url="https://horizonffxi.wiki/Category:Bonecraft/Adept", blocks={
      }},
      ["91-100"]={ rank="Veteran", url="https://horizonffxi.wiki/Category:Bonecraft/Veteran", blocks={
      }},
    },
  },
  ["Clothcraft"]={
    name="Clothcraft",
    page_url="https://horizonffxi.wiki/Category:Clothcraft",
    recipes_url="https://horizonffxi.wiki/Category:Clothcraft/All_Recipes",
    primary_guide_id="",
    primary_guide_title="",
    ranges={
      ["0-10"]={ rank="Amateur", url="https://horizonffxi.wiki/Category:Clothcraft/Amateur", blocks={
      }},
      ["11-20"]={ rank="Recruit", url="https://horizonffxi.wiki/Category:Clothcraft/Recruit", blocks={
      }},
      ["21-30"]={ rank="Initiate", url="https://horizonffxi.wiki/Category:Clothcraft/Initiate", blocks={
      }},
      ["31-40"]={ rank="Novice", url="https://horizonffxi.wiki/Category:Clothcraft/Novice", blocks={
      }},
      ["41-50"]={ rank="Apprentice", url="https://horizonffxi.wiki/Category:Clothcraft/Apprentice", blocks={
      }},
      ["51-60"]={ rank="Journeyman", url="https://horizonffxi.wiki/Category:Clothcraft/Journeyman", blocks={
      }},
      ["61-70"]={ rank="Craftsman", url="https://horizonffxi.wiki/Category:Clothcraft/Craftsman", blocks={
      }},
      ["71-80"]={ rank="Artisan", url="https://horizonffxi.wiki/Category:Clothcraft/Artisan", blocks={
      }},
      ["81-90"]={ rank="Adept", url="https://horizonffxi.wiki/Category:Clothcraft/Adept", blocks={
      }},
      ["91-100"]={ rank="Veteran", url="https://horizonffxi.wiki/Category:Clothcraft/Veteran", blocks={
      }},
    },
  },
  ["Cooking"]={
    name="Cooking",
    page_url="https://horizonffxi.wiki/Category:Cooking",
    recipes_url="https://horizonffxi.wiki/Category:Cooking/All_Recipes",
    primary_guide_id="wiki_1683",
    primary_guide_title="Cooking 0-60 Guide",
    ranges={
      ["0-10"]={ rank="Amateur", url="https://horizonffxi.wiki/Category:Cooking/Amateur", blocks={
        "0 - 6 Hard-Boiled Egg\010\010Hard-Boiled Egg (cap 6) \226\128\148 Fire Crystal \226\128\148 Bird Egg, Distilled Water\010\010Use Advanced support for at least the first level or two which should go quick.",
        "6 - 9 Pet Food Alpha\010\010Pet Food Alpha (cap 9) \226\128\148 Earth Crystal \226\128\148 Bird Egg, Hare Meat, Horo Flour, Distilled Water\010\010NPC results",
        "9 - 11 Sliced Sardine\010\010Sliced Sardine (cap 11) \226\128\148 Wind Crystal \226\128\148 Bastore Sardine\010\010This is where fishing comes in. You can skip straight to the next item on the list if you have Cod instead of Sardines",
      }},
      ["11-20"]={ rank="Recruit", url="https://horizonffxi.wiki/Category:Cooking/Recruit", blocks={
        "9 - 11 Sliced Sardine\010\010Sliced Sardine (cap 11) \226\128\148 Wind Crystal \226\128\148 Bastore Sardine\010\010This is where fishing comes in. You can skip straight to the next item on the list if you have Cod instead of Sardines",
        "11 - 13 Sliced Cod\010\010Sliced Cod (cap 13) \226\128\148 Wind Crystal \226\128\148 Tiger Cod\010\010NPC this as long as you want for decent gil",
        "13 - 19 Pet Food Beta\010\010Pet Food Beta (cap 19) \226\128\148 Earth Crystal \226\128\148 Karakul Meat, Apkallu Egg, Distilled Water, Horo Flour\010\010NPC results",
        "19 - 20 Selbina Butter\010\010Selbina Butter (cap 20) \226\128\148 Ice Crystal \226\128\148 Selbina Milk, Rock Salt\010\010Save this for the next bridge synth. Cost depends on price of Ices (Feb 17 patch nuked crystal price)",
        "20 - 22 Baked Popoto\010\010Baked Popoto (cap 22) \226\128\148 Fire Crystal \226\128\148 Popoto, Selbina Butter\010\010Use up the Selbina butter you made until you hit alteast 21. AH the leftover",
      }},
      ["21-30"]={ rank="Initiate", url="https://horizonffxi.wiki/Category:Cooking/Initiate", blocks={
        "20 - 22 Baked Popoto\010\010Baked Popoto (cap 22) \226\128\148 Fire Crystal \226\128\148 Popoto, Selbina Butter\010\010Use up the Selbina butter you made until you hit alteast 21. AH the leftover",
        "22 - 29 Insect Ball\010\010Insect Ball (cap 29) \226\128\148 Earth Crystal \226\128\148 Millioncorn, Little Worm, Distilled Water\010\010Advanced Support. This is a money maker sell it all on AH. It moves extremely fast since 75% of Horizon is fishing for Moats it seems.",
        "29 - 34 Black Bread\010\010Black Bread (cap 34) \226\128\148 Fire Crystal \226\128\148 Rye Flour, Rock Salt, Distilled Water\010\010Just NPC this for about break even.",
      }},
      ["31-40"]={ rank="Novice", url="https://horizonffxi.wiki/Category:Cooking/Novice", blocks={
        "29 - 34 Black Bread\010\010Black Bread (cap 34) \226\128\148 Fire Crystal \226\128\148 Rye Flour, Rock Salt, Distilled Water\010\010Just NPC this for about break even.",
        "34 - 39 Pet Food Delta\010\010Pet Food Delta (cap 39) \226\128\148 Earth Crystal \226\128\148 Bird Egg, Land Crab Meat, Rye Flour, Distilled Water\010\010NPC for a profit. At this point you might have actually made a total profit if you sold all your Insect Balls",
        "39 - 46 Pickled Herring\010\010Pickled Herring (cap 46) \226\128\148 Ice Crystal \226\128\148 Nosteau Herring, Dried Marjoram, Rock Salt\010\010Adv Support till 41. If you have been leveling fishing you can start the Herring at 29 or 25+4 from gear.\010NPC results",
      }},
      ["41-50"]={ rank="Apprentice", url="https://horizonffxi.wiki/Category:Cooking/Apprentice", blocks={
        "39 - 46 Pickled Herring\010\010Pickled Herring (cap 46) \226\128\148 Ice Crystal \226\128\148 Nosteau Herring, Dried Marjoram, Rock Salt\010\010Adv Support till 41. If you have been leveling fishing you can start the Herring at 29 or 25+4 from gear.\010NPC results",
        "46 - 50 Apple Pie\010\010Apple Pie (cap 48) \226\128\148 Fire Crystal \226\128\148 Lizard Egg, Faerie Apple, Pie Dough, Maple Sugar, Cinnamon\010\010Switching the egg increases the cap of the synth.\010These will sell eventually but you may just want to NPC them depending how fast you want to move onto the next synth.\010Can be skipped if you want to 6 gap the Crayfish Balls.\010You WILL lose a LOT of money on these.",
        "46 - 52 Crayfish Ball\010\010Crayfish Ball (cap 52) \226\128\148 Earth Crystal \226\128\148 Gold Lobster, San d'Orian Flour, Distilled Water\010\010Adv support if you skipped Apple Pies. This will sell fast on the AH and its relatively cheap. Again so many people are fishing.",
      }},
      ["51-60"]={ rank="Journeyman", url="https://horizonffxi.wiki/Category:Cooking/Journeyman", blocks={
        "46 - 52 Crayfish Ball\010\010Crayfish Ball (cap 52) \226\128\148 Earth Crystal \226\128\148 Gold Lobster, San d'Orian Flour, Distilled Water\010\010Adv support if you skipped Apple Pies. This will sell fast on the AH and its relatively cheap. Again so many people are fishing.",
        "52 - 59 Pet Food Zeta\010\010Pet Food Zeta (cap 59) \226\128\148 Earth Crystal \226\128\148 Lizard Egg, Coeurl Meat, San d'Orian Flour, Distilled Water\010\010Adv support until 55. Depending how expensive Coeurl Meat is on AH this can NPC for a profit. You will need to make a ton of this. Start in windy at the guild for Support. You can NPC it at the shop across the bridge from it and restock your Distilled Water as you need to.",
        "59 - 60 Yagudo Drink\010\010Yagudo Drink (cap 60) \226\128\148 Dark Crystal \226\128\148 Yagudo Cherry, Buburimu Grape x3\010\010Kolshushu vendor has ingredients",
      }},
      ["61-70"]={ rank="Craftsman", url="https://horizonffxi.wiki/Category:Cooking/Craftsman", blocks={
      }},
      ["71-80"]={ rank="Artisan", url="https://horizonffxi.wiki/Category:Cooking/Artisan", blocks={
      }},
      ["81-90"]={ rank="Adept", url="https://horizonffxi.wiki/Category:Cooking/Adept", blocks={
      }},
      ["91-100"]={ rank="Veteran", url="https://horizonffxi.wiki/Category:Cooking/Veteran", blocks={
      }},
    },
  },
  ["Fishing"]={
    name="Fishing",
    page_url="https://horizonffxi.wiki/Category:Fishing",
    recipes_url="https://horizonffxi.wiki/Category:Fishing/All_Fish",
    primary_guide_id="wiki_7265",
    primary_guide_title="Fishing Like a Pro 1-100 by Pepen",
    ranges={
      ["0-10"]={ rank="Amateur", url="https://horizonffxi.wiki/Category:Fishing/Amateur", blocks={
        "0-11\010\010Crayfish (7), Any Rod, Little Worm Most Freshwater bodies, I'd recommend catching these at Knightswell in West Ronfaure You can catch these while you get Moat Carp at the same time. Crayfish have limited uses outside of early cooking skill ups.\010Moat Carp (11) Hume Fishing Rod, Halcyon Rod, Insect Paste, West Ronfaure Knightswell- Same as above just with paste to isolate out the crayfish or use little worms if you don't mind getting crayfish too. Save all of your moat carp for Lu Shang's or sell on AH if you need gil. Save one for TEST ITEM\010Knightswell gets fished out constantly and is no longer the best place for Moat Carp.",
        "0-56\010\010Moat Carp (11) [[Hume Fishing Rod],Halcyon Rod, Insect Paste, West Ronfaure Knightswell- Keep one for TEST ITEM\010Tricolored Carp (27) [Hume Rod] Insect Paste Port San d'Oria- This set up will net you tricolored carp about 30% of the time and the rest will be Moat Carp and sometimes Gold Carp which may be hard to reel in so if you have trouble cancel them and any you do catch NPC.\010TEST ITEM Cheval Salmon (21) Buy from AH, it should be cheap.\010Nosteau Herring (39) Halcyon Rod, Sardine Balls, Lower Jeuno, Qufim Island- On the cliffside as you come out of the sea tunnel. Taking a break from Moat Carp to get within skill range of the next area, catch these to cap. -These are impossible to isolate from Tiger Cod which isn't a bad thing since they both sell quite well on the AH and for a nice profit compared to bait cost. If you have cooking close to 46 make them into Pickled Herrings and NPC for massive profits while you twirl your mustache with glee. I would recommend getting cooking to 13 and turning the Tiger Cod you catch into Sliced Cod To then NPC or sell on AH if that's more profitable but NPC should yield you about 5k per stack. Use all gil earned from this step to buy moat carp from the AH.\010TEST ITEM Gugru Tuna (41)- Buy off AH they're cheap and not worth the headache of catching yourself.\010Gold Carp (56) Halcyon Rod Insect Paste Windurst Woods- You will catch these as well as Moat Carp most of the time, NPC all Gold Carp for around ~300g each to buy more Moat Carp. Cap your skill here and you should have the 10,000 turned in by now or you should be very close. Once you have Lu Shang's please refer to the Lu Shang's section to continue.",
      }},
      ["11-20"]={ rank="Recruit", url="https://horizonffxi.wiki/Category:Fishing/Recruit", blocks={
        "0-11\010\010Crayfish (7), Any Rod, Little Worm Most Freshwater bodies, I'd recommend catching these at Knightswell in West Ronfaure You can catch these while you get Moat Carp at the same time. Crayfish have limited uses outside of early cooking skill ups.\010Moat Carp (11) Hume Fishing Rod, Halcyon Rod, Insect Paste, West Ronfaure Knightswell- Same as above just with paste to isolate out the crayfish or use little worms if you don't mind getting crayfish too. Save all of your moat carp for Lu Shang's or sell on AH if you need gil. Save one for TEST ITEM\010Knightswell gets fished out constantly and is no longer the best place for Moat Carp.",
        "11-27\010\010Yellow Globe (17) Halcyon Rod, Sabiki Rig, Mhaura OR Buburimu Peninsula- Caught by the truck loads with this set up in either zone, preferred Mhaura but if you find it over camped go to Buburimu instead. Used in alchemy for poison powder, sell on AH or NPC.\010Cheval Salmon (21) Halcyon Rod, Fly Lure East Ronfaure- Catch these just outside of Southern San d'oria in the stream until 18 or 20 if you prefer to stay here longer. Shining Trout will also bite here which may be difficult to reel in which is why I recommend you only stay here until 18. This is a TEST ITEM turn it in, NPC the rest and immediately head to the next target.\010Nebimonite (27) Halcyon Rod, Crayfish Ball/Shrimp Lure,Ship bound for Mhaura/Selbina- Ferry fishing can be a drag but catching these are very profitable even if crayfish balls are 6-7k per stack which is the bait I'd recommend although you CAN use the shrimp lure but it can hook fish that will break your rod/snap your line but you can cancel those, still not time efficient but figured I'd give an option. Fish these up til cap and sell on AH you should easily make the cost of bait back plus a nice profit. Fish on the stairs and angle your character diagonally to avoid the lower deck monsters if you are low level also have Sneak available too.\010TEST ITEM Giant Catfish Just buy this on the AH there should be plenty of stock.",
        "0-56\010\010Moat Carp (11) [[Hume Fishing Rod],Halcyon Rod, Insect Paste, West Ronfaure Knightswell- Keep one for TEST ITEM\010Tricolored Carp (27) [Hume Rod] Insect Paste Port San d'Oria- This set up will net you tricolored carp about 30% of the time and the rest will be Moat Carp and sometimes Gold Carp which may be hard to reel in so if you have trouble cancel them and any you do catch NPC.\010TEST ITEM Cheval Salmon (21) Buy from AH, it should be cheap.\010Nosteau Herring (39) Halcyon Rod, Sardine Balls, Lower Jeuno, Qufim Island- On the cliffside as you come out of the sea tunnel. Taking a break from Moat Carp to get within skill range of the next area, catch these to cap. -These are impossible to isolate from Tiger Cod which isn't a bad thing since they both sell quite well on the AH and for a nice profit compared to bait cost. If you have cooking close to 46 make them into Pickled Herrings and NPC for massive profits while you twirl your mustache with glee. I would recommend getting cooking to 13 and turning the Tiger Cod you catch into Sliced Cod To then NPC or sell on AH if that's more profitable but NPC should yield you about 5k per stack. Use all gil earned from this step to buy moat carp from the AH.\010TEST ITEM Gugru Tuna (41)- Buy off AH they're cheap and not worth the headache of catching yourself.\010Gold Carp (56) Halcyon Rod Insect Paste Windurst Woods- You will catch these as well as Moat Carp most of the time, NPC all Gold Carp for around ~300g each to buy more Moat Carp. Cap your skill here and you should have the 10,000 turned in by now or you should be very close. Once you have Lu Shang's please refer to the Lu Shang's section to continue.",
      }},
      ["21-30"]={ rank="Initiate", url="https://horizonffxi.wiki/Category:Fishing/Initiate", blocks={
        "11-27\010\010Yellow Globe (17) Halcyon Rod, Sabiki Rig, Mhaura OR Buburimu Peninsula- Caught by the truck loads with this set up in either zone, preferred Mhaura but if you find it over camped go to Buburimu instead. Used in alchemy for poison powder, sell on AH or NPC.\010Cheval Salmon (21) Halcyon Rod, Fly Lure East Ronfaure- Catch these just outside of Southern San d'oria in the stream until 18 or 20 if you prefer to stay here longer. Shining Trout will also bite here which may be difficult to reel in which is why I recommend you only stay here until 18. This is a TEST ITEM turn it in, NPC the rest and immediately head to the next target.\010Nebimonite (27) Halcyon Rod, Crayfish Ball/Shrimp Lure,Ship bound for Mhaura/Selbina- Ferry fishing can be a drag but catching these are very profitable even if crayfish balls are 6-7k per stack which is the bait I'd recommend although you CAN use the shrimp lure but it can hook fish that will break your rod/snap your line but you can cancel those, still not time efficient but figured I'd give an option. Fish these up til cap and sell on AH you should easily make the cost of bait back plus a nice profit. Fish on the stairs and angle your character diagonally to avoid the lower deck monsters if you are low level also have Sneak available too.\010TEST ITEM Giant Catfish Just buy this on the AH there should be plenty of stock.",
        "27-39\010\010Shining Trout (37) Halcyon Rod, Fly Lure, East Ronfaure- Same spot you caught the Cheval Salmon except now you can get those pesky trout easier. Fish these to cap and NPC everything or move on to the next fish instead.\010Nosteau Herring (39) Halcyon Rod, Sardine Balls, Lower Jeuno, Qufim Island- On the cliffside as you come out of the sea tunnel. -These are impossible to isolate from Tiger Cod which isn't a bad thing and I'd recommend you level cooking to 13 to turn these into sliced cod for better profit to sell to NPC. If you have cooking close to 46 make them into Pickled Herrings and NPC for massive profits while you twirl your mustache with glee.\010TEST ITEM Gugru Tuna (41)- Buy off AH they're cheap and not worth the headache of catching yourself.",
        "0-56\010\010Moat Carp (11) [[Hume Fishing Rod],Halcyon Rod, Insect Paste, West Ronfaure Knightswell- Keep one for TEST ITEM\010Tricolored Carp (27) [Hume Rod] Insect Paste Port San d'Oria- This set up will net you tricolored carp about 30% of the time and the rest will be Moat Carp and sometimes Gold Carp which may be hard to reel in so if you have trouble cancel them and any you do catch NPC.\010TEST ITEM Cheval Salmon (21) Buy from AH, it should be cheap.\010Nosteau Herring (39) Halcyon Rod, Sardine Balls, Lower Jeuno, Qufim Island- On the cliffside as you come out of the sea tunnel. Taking a break from Moat Carp to get within skill range of the next area, catch these to cap. -These are impossible to isolate from Tiger Cod which isn't a bad thing since they both sell quite well on the AH and for a nice profit compared to bait cost. If you have cooking close to 46 make them into Pickled Herrings and NPC for massive profits while you twirl your mustache with glee. I would recommend getting cooking to 13 and turning the Tiger Cod you catch into Sliced Cod To then NPC or sell on AH if that's more profitable but NPC should yield you about 5k per stack. Use all gil earned from this step to buy moat carp from the AH.\010TEST ITEM Gugru Tuna (41)- Buy off AH they're cheap and not worth the headache of catching yourself.\010Gold Carp (56) Halcyon Rod Insect Paste Windurst Woods- You will catch these as well as Moat Carp most of the time, NPC all Gold Carp for around ~300g each to buy more Moat Carp. Cap your skill here and you should have the 10,000 turned in by now or you should be very close. Once you have Lu Shang's please refer to the Lu Shang's section to continue.",
      }},
      ["31-40"]={ rank="Novice", url="https://horizonffxi.wiki/Category:Fishing/Novice", blocks={
        "27-39\010\010Shining Trout (37) Halcyon Rod, Fly Lure, East Ronfaure- Same spot you caught the Cheval Salmon except now you can get those pesky trout easier. Fish these to cap and NPC everything or move on to the next fish instead.\010Nosteau Herring (39) Halcyon Rod, Sardine Balls, Lower Jeuno, Qufim Island- On the cliffside as you come out of the sea tunnel. -These are impossible to isolate from Tiger Cod which isn't a bad thing and I'd recommend you level cooking to 13 to turn these into sliced cod for better profit to sell to NPC. If you have cooking close to 46 make them into Pickled Herrings and NPC for massive profits while you twirl your mustache with glee.\010TEST ITEM Gugru Tuna (41)- Buy off AH they're cheap and not worth the headache of catching yourself.",
        "39-61\010\010Cone Calamary (48) Halcyon Rod, Minnow, Batallia Downs- These will NPC pretty well and you'll also catch some Bluetail with this set up at the same time although you may lose some of them to \"lack of skill\" messages but nevertheless it's still worth your time as you'll grow into catching them here soon enough and the NPC profits start to get kind of crazy here.\010TEST ITEM: Monke-Onke- Buy off AH shouldn't be expensive\010Bluetail (55) Halcyon Rod, Minnow, Qufim Island The ice pond. This set up will isolate out the cone calamary and all of the other nasty fish that will break your rod/line. Fish these up until cap they NPC for 300g each and will be your primary target toward buying the moat carp for the Lu Shang's quest.\010Bhefhel Marlin (61) Mithran Fishing Rod/Composite Fishing Rod, Slice of Bluetail, Ship bound for Mhaura/Selbina- I decided to add these because I don't think they are too much trouble to catch but have been reported to break Halcyon Rods and Hume Rods. That could be a bonus if you're in the market of repairing broken rods with Alchemy or Woodworking. This combination will also target Cone Calamary as well as Silver Shark although you may or may not have difficulties catching them. These will be the \" | !\" bites you have chance at reeling in, the others will be legendary fish that will snap your line or break your rod and will be impossible to reel in so cancel those. These could also be a decent target to grind for your Lu Shang's Rod because they sell quickly for 2.5k each on the AH at the time of writing but your mileage may vary. Used for Inside the Belly for Pirate's Chart Quest TEST ITEM",
        "0-56\010\010Moat Carp (11) [[Hume Fishing Rod],Halcyon Rod, Insect Paste, West Ronfaure Knightswell- Keep one for TEST ITEM\010Tricolored Carp (27) [Hume Rod] Insect Paste Port San d'Oria- This set up will net you tricolored carp about 30% of the time and the rest will be Moat Carp and sometimes Gold Carp which may be hard to reel in so if you have trouble cancel them and any you do catch NPC.\010TEST ITEM Cheval Salmon (21) Buy from AH, it should be cheap.\010Nosteau Herring (39) Halcyon Rod, Sardine Balls, Lower Jeuno, Qufim Island- On the cliffside as you come out of the sea tunnel. Taking a break from Moat Carp to get within skill range of the next area, catch these to cap. -These are impossible to isolate from Tiger Cod which isn't a bad thing since they both sell quite well on the AH and for a nice profit compared to bait cost. If you have cooking close to 46 make them into Pickled Herrings and NPC for massive profits while you twirl your mustache with glee. I would recommend getting cooking to 13 and turning the Tiger Cod you catch into Sliced Cod To then NPC or sell on AH if that's more profitable but NPC should yield you about 5k per stack. Use all gil earned from this step to buy moat carp from the AH.\010TEST ITEM Gugru Tuna (41)- Buy off AH they're cheap and not worth the headache of catching yourself.\010Gold Carp (56) Halcyon Rod Insect Paste Windurst Woods- You will catch these as well as Moat Carp most of the time, NPC all Gold Carp for around ~300g each to buy more Moat Carp. Cap your skill here and you should have the 10,000 turned in by now or you should be very close. Once you have Lu Shang's please refer to the Lu Shang's section to continue.",
      }},
      ["41-50"]={ rank="Apprentice", url="https://horizonffxi.wiki/Category:Fishing/Apprentice", blocks={
        "39-61\010\010Cone Calamary (48) Halcyon Rod, Minnow, Batallia Downs- These will NPC pretty well and you'll also catch some Bluetail with this set up at the same time although you may lose some of them to \"lack of skill\" messages but nevertheless it's still worth your time as you'll grow into catching them here soon enough and the NPC profits start to get kind of crazy here.\010TEST ITEM: Monke-Onke- Buy off AH shouldn't be expensive\010Bluetail (55) Halcyon Rod, Minnow, Qufim Island The ice pond. This set up will isolate out the cone calamary and all of the other nasty fish that will break your rod/line. Fish these up until cap they NPC for 300g each and will be your primary target toward buying the moat carp for the Lu Shang's quest.\010Bhefhel Marlin (61) Mithran Fishing Rod/Composite Fishing Rod, Slice of Bluetail, Ship bound for Mhaura/Selbina- I decided to add these because I don't think they are too much trouble to catch but have been reported to break Halcyon Rods and Hume Rods. That could be a bonus if you're in the market of repairing broken rods with Alchemy or Woodworking. This combination will also target Cone Calamary as well as Silver Shark although you may or may not have difficulties catching them. These will be the \" | !\" bites you have chance at reeling in, the others will be legendary fish that will snap your line or break your rod and will be impossible to reel in so cancel those. These could also be a decent target to grind for your Lu Shang's Rod because they sell quickly for 2.5k each on the AH at the time of writing but your mileage may vary. Used for Inside the Belly for Pirate's Chart Quest TEST ITEM",
        "0-56\010\010Moat Carp (11) [[Hume Fishing Rod],Halcyon Rod, Insect Paste, West Ronfaure Knightswell- Keep one for TEST ITEM\010Tricolored Carp (27) [Hume Rod] Insect Paste Port San d'Oria- This set up will net you tricolored carp about 30% of the time and the rest will be Moat Carp and sometimes Gold Carp which may be hard to reel in so if you have trouble cancel them and any you do catch NPC.\010TEST ITEM Cheval Salmon (21) Buy from AH, it should be cheap.\010Nosteau Herring (39) Halcyon Rod, Sardine Balls, Lower Jeuno, Qufim Island- On the cliffside as you come out of the sea tunnel. Taking a break from Moat Carp to get within skill range of the next area, catch these to cap. -These are impossible to isolate from Tiger Cod which isn't a bad thing since they both sell quite well on the AH and for a nice profit compared to bait cost. If you have cooking close to 46 make them into Pickled Herrings and NPC for massive profits while you twirl your mustache with glee. I would recommend getting cooking to 13 and turning the Tiger Cod you catch into Sliced Cod To then NPC or sell on AH if that's more profitable but NPC should yield you about 5k per stack. Use all gil earned from this step to buy moat carp from the AH.\010TEST ITEM Gugru Tuna (41)- Buy off AH they're cheap and not worth the headache of catching yourself.\010Gold Carp (56) Halcyon Rod Insect Paste Windurst Woods- You will catch these as well as Moat Carp most of the time, NPC all Gold Carp for around ~300g each to buy more Moat Carp. Cap your skill here and you should have the 10,000 turned in by now or you should be very close. Once you have Lu Shang's please refer to the Lu Shang's section to continue.",
      }},
      ["51-60"]={ rank="Journeyman", url="https://horizonffxi.wiki/Category:Fishing/Journeyman", blocks={
        "39-61\010\010Cone Calamary (48) Halcyon Rod, Minnow, Batallia Downs- These will NPC pretty well and you'll also catch some Bluetail with this set up at the same time although you may lose some of them to \"lack of skill\" messages but nevertheless it's still worth your time as you'll grow into catching them here soon enough and the NPC profits start to get kind of crazy here.\010TEST ITEM: Monke-Onke- Buy off AH shouldn't be expensive\010Bluetail (55) Halcyon Rod, Minnow, Qufim Island The ice pond. This set up will isolate out the cone calamary and all of the other nasty fish that will break your rod/line. Fish these up until cap they NPC for 300g each and will be your primary target toward buying the moat carp for the Lu Shang's quest.\010Bhefhel Marlin (61) Mithran Fishing Rod/Composite Fishing Rod, Slice of Bluetail, Ship bound for Mhaura/Selbina- I decided to add these because I don't think they are too much trouble to catch but have been reported to break Halcyon Rods and Hume Rods. That could be a bonus if you're in the market of repairing broken rods with Alchemy or Woodworking. This combination will also target Cone Calamary as well as Silver Shark although you may or may not have difficulties catching them. These will be the \" | !\" bites you have chance at reeling in, the others will be legendary fish that will snap your line or break your rod and will be impossible to reel in so cancel those. These could also be a decent target to grind for your Lu Shang's Rod because they sell quickly for 2.5k each on the AH at the time of writing but your mileage may vary. Used for Inside the Belly for Pirate's Chart Quest TEST ITEM",
        "55-76\010\010Crescent Fish (69) Fly Lure, Yuhtunga Jungle, East Sarutabaruta- These NPC for just over 400g each and you can isolate them in East Saruta at the west lake. Yuhtunga is also a decent option but if you want to isolate them you'll have to go through Ifrit's Cauldron to get to the waterfall location. Otherwise you may catch other fish. I haven't gone there personally but I've heard good things. I stayed In E.Saruta until about 61 and moved onto Silver Shark. The stock here can be iffy especially if other players are around so you may have to wait until they refresh every now and then.\010TEST ITEM Bladefish- Catch in East Sarutabaruta with Meatballs (Seaside) or buy off AH if you want to save time\010Silver Shark (76) Meatball, Batallia Downs- These use to be killer profits at 500g each to an NPC but on Horizon it was nerfed to about 225g each so not great but it will still cover the cost of bait. I spent 8k per stack on meatballs and still made a small profit per stack. I stayed here til about 71 but you could stay to cap if you want.",
        "0-56\010\010Moat Carp (11) [[Hume Fishing Rod],Halcyon Rod, Insect Paste, West Ronfaure Knightswell- Keep one for TEST ITEM\010Tricolored Carp (27) [Hume Rod] Insect Paste Port San d'Oria- This set up will net you tricolored carp about 30% of the time and the rest will be Moat Carp and sometimes Gold Carp which may be hard to reel in so if you have trouble cancel them and any you do catch NPC.\010TEST ITEM Cheval Salmon (21) Buy from AH, it should be cheap.\010Nosteau Herring (39) Halcyon Rod, Sardine Balls, Lower Jeuno, Qufim Island- On the cliffside as you come out of the sea tunnel. Taking a break from Moat Carp to get within skill range of the next area, catch these to cap. -These are impossible to isolate from Tiger Cod which isn't a bad thing since they both sell quite well on the AH and for a nice profit compared to bait cost. If you have cooking close to 46 make them into Pickled Herrings and NPC for massive profits while you twirl your mustache with glee. I would recommend getting cooking to 13 and turning the Tiger Cod you catch into Sliced Cod To then NPC or sell on AH if that's more profitable but NPC should yield you about 5k per stack. Use all gil earned from this step to buy moat carp from the AH.\010TEST ITEM Gugru Tuna (41)- Buy off AH they're cheap and not worth the headache of catching yourself.\010Gold Carp (56) Halcyon Rod Insect Paste Windurst Woods- You will catch these as well as Moat Carp most of the time, NPC all Gold Carp for around ~300g each to buy more Moat Carp. Cap your skill here and you should have the 10,000 turned in by now or you should be very close. Once you have Lu Shang's please refer to the Lu Shang's section to continue.",
      }},
      ["61-70"]={ rank="Craftsman", url="https://horizonffxi.wiki/Category:Fishing/Craftsman", blocks={
        "39-61\010\010Cone Calamary (48) Halcyon Rod, Minnow, Batallia Downs- These will NPC pretty well and you'll also catch some Bluetail with this set up at the same time although you may lose some of them to \"lack of skill\" messages but nevertheless it's still worth your time as you'll grow into catching them here soon enough and the NPC profits start to get kind of crazy here.\010TEST ITEM: Monke-Onke- Buy off AH shouldn't be expensive\010Bluetail (55) Halcyon Rod, Minnow, Qufim Island The ice pond. This set up will isolate out the cone calamary and all of the other nasty fish that will break your rod/line. Fish these up until cap they NPC for 300g each and will be your primary target toward buying the moat carp for the Lu Shang's quest.\010Bhefhel Marlin (61) Mithran Fishing Rod/Composite Fishing Rod, Slice of Bluetail, Ship bound for Mhaura/Selbina- I decided to add these because I don't think they are too much trouble to catch but have been reported to break Halcyon Rods and Hume Rods. That could be a bonus if you're in the market of repairing broken rods with Alchemy or Woodworking. This combination will also target Cone Calamary as well as Silver Shark although you may or may not have difficulties catching them. These will be the \" | !\" bites you have chance at reeling in, the others will be legendary fish that will snap your line or break your rod and will be impossible to reel in so cancel those. These could also be a decent target to grind for your Lu Shang's Rod because they sell quickly for 2.5k each on the AH at the time of writing but your mileage may vary. Used for Inside the Belly for Pirate's Chart Quest TEST ITEM",
        "55-76\010\010Crescent Fish (69) Fly Lure, Yuhtunga Jungle, East Sarutabaruta- These NPC for just over 400g each and you can isolate them in East Saruta at the west lake. Yuhtunga is also a decent option but if you want to isolate them you'll have to go through Ifrit's Cauldron to get to the waterfall location. Otherwise you may catch other fish. I haven't gone there personally but I've heard good things. I stayed In E.Saruta until about 61 and moved onto Silver Shark. The stock here can be iffy especially if other players are around so you may have to wait until they refresh every now and then.\010TEST ITEM Bladefish- Catch in East Sarutabaruta with Meatballs (Seaside) or buy off AH if you want to save time\010Silver Shark (76) Meatball, Batallia Downs- These use to be killer profits at 500g each to an NPC but on Horizon it was nerfed to about 225g each so not great but it will still cover the cost of bait. I spent 8k per stack on meatballs and still made a small profit per stack. I stayed here til about 71 but you could stay to cap if you want.",
      }},
      ["71-80"]={ rank="Artisan", url="https://horizonffxi.wiki/Category:Fishing/Artisan", blocks={
        "55-76\010\010Crescent Fish (69) Fly Lure, Yuhtunga Jungle, East Sarutabaruta- These NPC for just over 400g each and you can isolate them in East Saruta at the west lake. Yuhtunga is also a decent option but if you want to isolate them you'll have to go through Ifrit's Cauldron to get to the waterfall location. Otherwise you may catch other fish. I haven't gone there personally but I've heard good things. I stayed In E.Saruta until about 61 and moved onto Silver Shark. The stock here can be iffy especially if other players are around so you may have to wait until they refresh every now and then.\010TEST ITEM Bladefish- Catch in East Sarutabaruta with Meatballs (Seaside) or buy off AH if you want to save time\010Silver Shark (76) Meatball, Batallia Downs- These use to be killer profits at 500g each to an NPC but on Horizon it was nerfed to about 225g each so not great but it will still cover the cost of bait. I spent 8k per stack on meatballs and still made a small profit per stack. I stayed here til about 71 but you could stay to cap if you want.",
        "71-96\010\010Bastore Bream (86) Shrimp Lure, Port Windurst, Port Bastok, I haven't found either one to be the better zone but I lean towards Windurst. Both zones have a pretty mediocre bite rate but at ~7k per stack to an NPC it's hard to complain about slow skill ups.\010Black Sole (96) Sinking Minnow Qufim Island NE cliffside in front of Delkfutt's Tower OR NW cliff. Well, you made it to the promised lands... These will NPC for about 8k per stack similar to Breams BUT I'd advise selling these on the AH instead as they're used in Sole Sushi and sell like hot cakes for about 9-10k per stack. If you catch them faster than you can sell them, then by all means NPC excess.\010TEST ITEMS Your final test items Three-eyed Fish (can be caught in the same spot as Nosteau Herrings and Tiger Cod) and Gigant Squid Both of which sell well on the AH",
      }},
      ["81-90"]={ rank="Adept", url="https://horizonffxi.wiki/Category:Fishing/Adept", blocks={
        "71-96\010\010Bastore Bream (86) Shrimp Lure, Port Windurst, Port Bastok, I haven't found either one to be the better zone but I lean towards Windurst. Both zones have a pretty mediocre bite rate but at ~7k per stack to an NPC it's hard to complain about slow skill ups.\010Black Sole (96) Sinking Minnow Qufim Island NE cliffside in front of Delkfutt's Tower OR NW cliff. Well, you made it to the promised lands... These will NPC for about 8k per stack similar to Breams BUT I'd advise selling these on the AH instead as they're used in Sole Sushi and sell like hot cakes for about 9-10k per stack. If you catch them faster than you can sell them, then by all means NPC excess.\010TEST ITEMS Your final test items Three-eyed Fish (can be caught in the same spot as Nosteau Herrings and Tiger Cod) and Gigant Squid Both of which sell well on the AH",
      }},
      ["91-100"]={ rank="Veteran", url="https://horizonffxi.wiki/Category:Fishing/Veteran", blocks={
        "71-96\010\010Bastore Bream (86) Shrimp Lure, Port Windurst, Port Bastok, I haven't found either one to be the better zone but I lean towards Windurst. Both zones have a pretty mediocre bite rate but at ~7k per stack to an NPC it's hard to complain about slow skill ups.\010Black Sole (96) Sinking Minnow Qufim Island NE cliffside in front of Delkfutt's Tower OR NW cliff. Well, you made it to the promised lands... These will NPC for about 8k per stack similar to Breams BUT I'd advise selling these on the AH instead as they're used in Sole Sushi and sell like hot cakes for about 9-10k per stack. If you catch them faster than you can sell them, then by all means NPC excess.\010TEST ITEMS Your final test items Three-eyed Fish (can be caught in the same spot as Nosteau Herrings and Tiger Cod) and Gigant Squid Both of which sell well on the AH",
      }},
    },
  },
  ["Goldsmithing"]={
    name="Goldsmithing",
    page_url="https://horizonffxi.wiki/Category:Goldsmithing",
    recipes_url="https://horizonffxi.wiki/Category:Goldsmithing/All_Recipes",
    primary_guide_id="",
    primary_guide_title="",
    ranges={
      ["0-10"]={ rank="Amateur", url="https://horizonffxi.wiki/Category:Goldsmithing/Amateur", blocks={
      }},
      ["11-20"]={ rank="Recruit", url="https://horizonffxi.wiki/Category:Goldsmithing/Recruit", blocks={
      }},
      ["21-30"]={ rank="Initiate", url="https://horizonffxi.wiki/Category:Goldsmithing/Initiate", blocks={
      }},
      ["31-40"]={ rank="Novice", url="https://horizonffxi.wiki/Category:Goldsmithing/Novice", blocks={
      }},
      ["41-50"]={ rank="Apprentice", url="https://horizonffxi.wiki/Category:Goldsmithing/Apprentice", blocks={
      }},
      ["51-60"]={ rank="Journeyman", url="https://horizonffxi.wiki/Category:Goldsmithing/Journeyman", blocks={
      }},
      ["61-70"]={ rank="Craftsman", url="https://horizonffxi.wiki/Category:Goldsmithing/Craftsman", blocks={
      }},
      ["71-80"]={ rank="Artisan", url="https://horizonffxi.wiki/Category:Goldsmithing/Artisan", blocks={
      }},
      ["81-90"]={ rank="Adept", url="https://horizonffxi.wiki/Category:Goldsmithing/Adept", blocks={
      }},
      ["91-100"]={ rank="Veteran", url="https://horizonffxi.wiki/Category:Goldsmithing/Veteran", blocks={
      }},
    },
  },
  ["Leathercraft"]={
    name="Leathercraft",
    page_url="https://horizonffxi.wiki/Category:Leathercraft",
    recipes_url="https://horizonffxi.wiki/Category:Leathercraft/All_Recipes",
    primary_guide_id="",
    primary_guide_title="",
    ranges={
      ["0-10"]={ rank="Amateur", url="https://horizonffxi.wiki/Category:Leathercraft/Amateur", blocks={
      }},
      ["11-20"]={ rank="Recruit", url="https://horizonffxi.wiki/Category:Leathercraft/Recruit", blocks={
      }},
      ["21-30"]={ rank="Initiate", url="https://horizonffxi.wiki/Category:Leathercraft/Initiate", blocks={
      }},
      ["31-40"]={ rank="Novice", url="https://horizonffxi.wiki/Category:Leathercraft/Novice", blocks={
      }},
      ["41-50"]={ rank="Apprentice", url="https://horizonffxi.wiki/Category:Leathercraft/Apprentice", blocks={
      }},
      ["51-60"]={ rank="Journeyman", url="https://horizonffxi.wiki/Category:Leathercraft/Journeyman", blocks={
      }},
      ["61-70"]={ rank="Craftsman", url="https://horizonffxi.wiki/Category:Leathercraft/Craftsman", blocks={
      }},
      ["71-80"]={ rank="Artisan", url="https://horizonffxi.wiki/Category:Leathercraft/Artisan", blocks={
      }},
      ["81-90"]={ rank="Adept", url="https://horizonffxi.wiki/Category:Leathercraft/Adept", blocks={
      }},
      ["91-100"]={ rank="Veteran", url="https://horizonffxi.wiki/Category:Leathercraft/Veteran", blocks={
      }},
    },
  },
  ["Smithing"]={
    name="Smithing",
    page_url="https://horizonffxi.wiki/Category:Smithing",
    recipes_url="https://horizonffxi.wiki/Category:Smithing/All_Recipes",
    primary_guide_id="wiki_16013",
    primary_guide_title="Smithing guide by Ctownwood and comments",
    ranges={
      ["0-10"]={ rank="Amateur", url="https://horizonffxi.wiki/Category:Smithing/Amateur", blocks={
        "0-10\010\010Bronze Ingot (2)-Fire Crystal, Copper Ore x3, Tin Ore--Cheap and easy to do. Now, pretty cheap to get on AH and from Guilds as well. Save them if you make them, but you can skip .\010Bronze Sheet (4)-Fire Crystal, Bronze Ingot--Easy, cheap, shouldn't take more than 2-3 stacks from 2 or 3-4 stacks from 0 skill. You can make these or buy these. Pretty cheap at this point.\010Hatchet (8)-Fire Crystal, Maple Lumber, Bronze Ingot x2--Woodworking sub of 2, which isn't a problem. At lowest prices from Guilds, these are cheaper to make, before HQs, than they are to buy from NPCs. Make a couple of stacks to sell on AH for various quests/missions.\010Bronze Scales (10)-Wind Crystal, Bronze Sheet--Make to cap, sell them at a loss to an NPC, and get over it. There isn't a lot here but the good news is that this is cheap as anything you'll see, despite the increase in Wind Crystal prices.\010TEST ITEM: Xiphos(8): Fire Crystal, Giant Femur, Bronze Ingot x2--Get one somehow. Bonecraft 2 as a sub might make you fail but only maybe.",
      }},
      ["11-20"]={ rank="Recruit", url="https://horizonffxi.wiki/Category:Smithing/Recruit", blocks={
        "11-20\010\010Boltheads (14)-Wind Crystal, Bronze Ingot, Animal Glue, [additive]--All of these aside from Bronze Bolt Heads require some level of Alchemy to make the [additive] and then to make the boltheads. This is the principle reason why my Alchemy-mule got his Smithing skill to 15. The list is Blind_Bolt_Heads (31), Acid_Bolt_Heads (45), Holy_Bolt_Heads (53), Sleep_Bolt_Heads (67), Venom_Bolt_Heads (76), and Bloody_Bolt_Heads (81). Make to cap, one or multiple types.\010Note: You can try to make the plain Bronze_Bolt_Heads from just Bronze Ingots, but they don't sell well. However, it's easier that way, if you don't have the Alchemy.\01015-19 lightning crystal + Goblin Mail to get closer to Iron Ingot, imo --Pyrra0 (talk) 01:52, 10 March 2024 (UTC)\010This is a stopping point to level alchemy to 40 and goldsmithing to 24 if you plan to make bullets. If you plan to make bolts, i'm not sure tbh --Pyrra0 (talk) 05:46, 9 March 2024 (UTC)\010Iron Ingot (20)-Fire Crystal, Iron Ore x4--This will be the only time that you make these. Ever. The ore costs 675 at the guild, check the AH for cheaper samples, and the Ingots cost 2700 each (675 x4 = 2700), so buying the ingots is cheaper but you need the skill for now and it only costs a crystal per attempt. Never, ever ever buy either for more than the listed prices.\010Paktong Ingot (20)-Fire Crystal, Zinc Ore, Copper Ore x2, Kopparnickel Ore--These are a good example of that \"profitable but slow\" synth. It's used almost exclusively for Gobbiebag quest and the ore is a drop from Bugbears in Movalpolos, so don't count on large supplies or high demand, but consider it if you see a chance.\010TEST ITEM: Aspis: Fire Crystal, Ash Lumber, Bronze Sheet x2--Easy enough to make if you are in Sandy or buy from the Guild if you are in Bastok.",
      }},
      ["21-30"]={ rank="Initiate", url="https://horizonffxi.wiki/Category:Smithing/Initiate", blocks={
        "21-30\010\010Iron Sheet (22)-Fire Crystal, Iron Ingot--Time was, that this up-coming series was extremely profitable. Now, not as profitable, but it is the best way to get rid of your newly-made Iron Ingots. Don't sell the Sheets yet, though. Just cap on these before moving onto Scales/Makibishi.\010Update: After passing 26 in skill, you can turn Iron Ingots into Sheets at a profit. People use a ton of Iron Sheets from mid 30s to 45 and then from mid 50s to 66.\010Makibishi (23)-Wind Crystal, Iron Scales--Ironically, this is the third of the three synths for disposing of your Iron Ingots but second in terms of skill. Turn one Sheet into a Scale then into a Makibishi in order to attempt to maximize your skill-ups. A good item for Ninjas spamming the wheel.\010This is a stopping point to get past Iron Bullet in alchemy(45) then Steel Bullet(50). You will now start making more Steel Ingot from this point forward than Iron Ingot given the skill difference. Plan accordingly. Protip: iron bullets are easier to make but sells faster because its lower lvl while steel bullets is used in 75/endgame, harder to acquire in theory and sells slower. --Pyrra0 (talk) 05:46, 9 March 2024 (UTC)\010Iron Scales (26)-Wind Crystal, Iron Sheet--Second in the Iron Ingot Sequence, but the top in terms of skill. Make one, then turn it into Makibishi. Once you hit cap on Makibishi, just make these until you cap, then make them into Makibishi.\010Steel Bullet (30)-Fire Crystal, Steel Ingot, Firesand--Alchemy 49 as the main-craft and you can't make Steel Ingots yet but look for them on the AH. This isn't cheap, around 50-60k per stack made, but profitable. These are the premiere bullets for non-Rangers. NOT AVAILABLE ON Horizon",
        "21-30\010\010TEST ITEM: Bilbo: Fire Crystal, Silver Ingot, Iron Ingot: Goldsmithing 7 as a sub-craft, but you might be able to buy one on the AH for cheaper than it takes to make this.",
      }},
      ["31-40"]={ rank="Novice", url="https://horizonffxi.wiki/Category:Smithing/Novice", blocks={
        "31-40\010\010Iron Cuisses (35)-Earth Crystal, Iron Scales x2, Cotton Thread, Leather Trousers--Camp the AH for Iron Scales, at 2k each or less. Make these in Sandy and beware of the sub-craft of Leathercraft 5. If you do all that, these NPC to the Guildshop at break-even or better. Even if you have to make your own scales, cap on these.\010Iron Greaves (36)-Earth Crystal, Iron Scales x2, Cotton Thread, Leather Highboots--Same pattern you'll use again with Steel Scales, same sub-craft of Leathercraft 5, same principles of camping the AH, etc. However, just use left-over Iron Scales from Iron Cuisses because the Greaves cost almost as much to make as the Cuisses but NPC back for less.\010War Pick (38)-Fire Crystal, Ash Lumber, Steel Ingot--Get the Steel Ingot for around 3.5k or so and this will NPC at Sandy guild for a profit, in batches. Woodworking 6, which can Ash Lumber, is required as a sub-craft. Easier than finding cheap Iron Scales, but not sure on the Guilds' tolerance for a lot of these at once.\010TEST ITEM: War Pick: Fire Crystal, Steel Ingot, Ash Lumber: Beware the Woodworking 6 sub-craft; it's just enough to cause issues. Make or buy it, whichever is cheaper.",
      }},
      ["41-50"]={ rank="Apprentice", url="https://horizonffxi.wiki/Category:Smithing/Apprentice", blocks={
        "41-50\010\010Iron Mittens (41)-Earth Crystal, Iron Sheet, Lizard Skin--Leathercraft 10 as a sub-craft. A cause for concern if your skill is only at 5, but not that big a worry otherwise. This is the first Iron Sheet armor you'll be making and begins your need for large amounts of Iron Sheets. The Iron Mittens sell to NPCs at the Bastok Guild this time, for almost the cost of an Iron Ingot. Make these until 39-40 tops.\010Iron Subligar (45)-Earth Crystal, Iron Sheet, Lizard Skin, Cotton Cloth--Leathercraft 12 this time, so make sure you have turned in a Rabbit Mantle to the Leathercraft Guild in Sandy. These sell for so much more than the Iron Mittens, but barely break-even at best. Make these to cap for the simple reason that it's better than the alternatives.\010Mythril Pick (47)-Fire Crystal, Mythril Ingot, Elm Lumber--TEST ITEM. These sell for between 7400-8300 (depending on recent sales to the Guildshop) and cost 7k-ish to make, depending on how cheaply you can get the lumber and the ingots. Woodworking 8 as a subcraft. Frankly, again, if you can NPC these at a profit while getting skill, that's the best bet by far. Also, sell decently considering their use in getting Map of Mount Zhayolm.",
      }},
      ["51-60"]={ rank="Journeyman", url="https://horizonffxi.wiki/Category:Smithing/Journeyman", blocks={
        "51-60\010\010Darksteel Ingot (52)-Fire Crystal, Darksteel Ore, Iron Ore x3--Back in the profits again. A commonly used craft item that sells well in singles and stacks. Used in Gobbiebag quests as well. The only thing to beware is that these are a common product of Mine-bots and Gil-Farmers that use Mining. Remember to never buy Iron Ore above 675, factor that into what you pay for the Darksteel Ore, and craft like a maniac. Cap on these and enjoy the best way to regenerate your gil that Smithing can offer.\010Gorget (53)-Fire Crystal, Iron Sheet, Sheep Leather--A good level of skill for almost break-even. This was recommended to me by Danallen for those too cheap or too poor for a ton of Darksteel Ores. Also, a good extra level. The ingots are 2.7k, the gorgets sell for 3060 at the Bastok Guild, so 360 gil for a Fire Crystal and Sheep Leather.\010Darksteel Sheet (55)-Fire Crystal, Darksteel Ingot--Adding these into the mix kinda late, but a bad sequence of Steel Cuisses synths wasted a ton of carefully-hoarded Steel Scales, despite being a Full Moon + Darksday, so I need the extra little oomph provided.\010Steel Cuisses (55)-Earth Crystal, Steel Scales x2, Cotton Thread, Leather Trousers--Camp the AH for Steel Scales, at 2k each or less. Make these in Sandy and be aware of the sub-craft of Leathercraft 5. However, you do all that, these NPC to the Guildshop at break-even or better. Cap on these. (Seems familiar? I copy-and-pasted the Iron Cuisses text here and changed Iron to Steel; it really was that simple).",
        "51-60\010\010Steel Greaves (56)-Earth Crystal, Steel Scales x2, Cotton Thread, Leather Highboots--Same pattern you used with Iron Scales, same sub-craft of Leathercraft 5, same principles of camping the AH, etc. The difference between this and Iron Greaves is that this extra level isn't optional this time as the next craft I recommend is a bit more advanced. Quite a bit more...\010TEST ITEM: Darksteel Falchion--Fire Crystal, Steel Ingot, Darksteel Ingot x3: Make or buy as you can. Last one before 70.",
        "Cheaper Bridge from 56~60?\010\010Dweomer Steel (Smithing 67)\010Fire Crystal\0103 Iron Ore\0101 Swamp Ore\010Either recipe you use, you're basically converting gil to skillups. Since the introduction of the Campaign Union system, I found that I could get my Swamp ores cheaply, in most cases less than the price of Iron Ore from the guild. If you make Nodowa, that's 4 Iron Ores for the Ingot (assuming you produce the sheets yourself) plus 2 Fire Crystals (1 to make the ingot, 1 to make the sheet) plus a Silk Thread and an Earth Crystal. When the Kupower \"Artisan's Advantage\" was in effect I could break even on that synth because I wasn't losing too many mats, but I found the Dweomer ingots to be much more cost-efficient and inventory-friendly means to getting 60.\010(I feel really funny even posting this, Ctown... your guides are Holy Writ to me. Thanks for helping make Asura and FFXI great! ^^) Aeryck's Obnoxious Sig 22:33, November 26, 2009 (UTC)\010Good idea, I am adding this to the guide. However, Nodowa sell for 2.7k~ish and Dweomer Steel for 1k~ish, so the Nodowa make up for the cost of Silk Thread + Earth Crystal extra. And you should be buying the Iron Ingots from the Guild directly, once you finish making them. --Ctownwoody 23:29, November 26, 2009 (UTC)",
      }},
      ["61-70"]={ rank="Craftsman", url="https://horizonffxi.wiki/Category:Smithing/Craftsman", blocks={
        "61-70\010\010Nodowa (66)-Earth Crystal, Silk Thread, Iron Sheet--Yes, you are reading this right. A 10-level jump. And boy do these eat your gil. But they are decently close to break-even if you sell them to Silver Owl of the Tenshodo in Port Bastok (you are a member, right?). The only good news I can offer is that the sheer scale of the jump offers a better chance at .2 skill-ups than previously.\010Dweomer Steel (67)-Fire Crystal, Swamp Ore, Iron Ore x3--The Swamp Ore is from Unions in Campaign Battle, fairly common and cheap on the AH. While it costs less than Nodowa to make, it sells for less as well and space can become an issue if you are trying to do a ton at once. Still, 60+ is kinda barren for Smithing at this stretch. Technically used for Succor to the Sidhe items, 8~9 of them at 67 or less, that you can sell to friends.\010Darksteel Cap (72)-Fire Crystal, Darksteel Sheet, Tiger Leather x2--These are used as the base item in about 3-4 high level Bonecraft synths, and thus sell decently at a profit. Subcraft of Leather is in the mid/upper-30s, but this synth only makes sense if you can make your own leather (right now, that's 1/3~1/4 the price of buying on AH). Only make to AH, and a better use of Darksteel Sheets than I've found for skilling up.\010Darksteel Pick (73)-Fire Crystal, Elm Lumber, Darksteel Ingot--These NPC for over 10k to the right guild NPC and the ingots are cheaper than ever. Great way to get to 70+.",
      }},
      ["71-80"]={ rank="Artisan", url="https://horizonffxi.wiki/Category:Smithing/Artisan", blocks={
      }},
      ["81-90"]={ rank="Adept", url="https://horizonffxi.wiki/Category:Smithing/Adept", blocks={
      }},
      ["91-100"]={ rank="Veteran", url="https://horizonffxi.wiki/Category:Smithing/Veteran", blocks={
      }},
    },
  },
  ["Woodworking"]={
    name="Woodworking",
    page_url="https://horizonffxi.wiki/Category:Woodworking",
    recipes_url="https://horizonffxi.wiki/Category:Woodworking/All_Recipes",
    primary_guide_id="",
    primary_guide_title="",
    ranges={
      ["0-10"]={ rank="Amateur", url="https://horizonffxi.wiki/Category:Woodworking/Amateur", blocks={
      }},
      ["11-20"]={ rank="Recruit", url="https://horizonffxi.wiki/Category:Woodworking/Recruit", blocks={
      }},
      ["21-30"]={ rank="Initiate", url="https://horizonffxi.wiki/Category:Woodworking/Initiate", blocks={
      }},
      ["31-40"]={ rank="Novice", url="https://horizonffxi.wiki/Category:Woodworking/Novice", blocks={
      }},
      ["41-50"]={ rank="Apprentice", url="https://horizonffxi.wiki/Category:Woodworking/Apprentice", blocks={
      }},
      ["51-60"]={ rank="Journeyman", url="https://horizonffxi.wiki/Category:Woodworking/Journeyman", blocks={
      }},
      ["61-70"]={ rank="Craftsman", url="https://horizonffxi.wiki/Category:Woodworking/Craftsman", blocks={
      }},
      ["71-80"]={ rank="Artisan", url="https://horizonffxi.wiki/Category:Woodworking/Artisan", blocks={
      }},
      ["81-90"]={ rank="Adept", url="https://horizonffxi.wiki/Category:Woodworking/Adept", blocks={
      }},
      ["91-100"]={ rank="Veteran", url="https://horizonffxi.wiki/Category:Woodworking/Veteran", blocks={
      }},
    },
  },
}